# Aliases

docker-rm () {
  docker stop $1 && docker rm $1
}

docker-rm-rf () {
  docker stop $(docker ps -a -q) && \
  docker rm $(docker ps -a -q)
}

docker-start() {
  docker-machine start default && \
  eval $(docker-machine env)
}

docker-restart() {
  docker-machine stop default && \
  docker-start
}

docker-sync-clock() {
  docker run -it --rm --privileged --pid=host debian nsenter -t 1 -m -u -n -i date -u $(date -u +%m%d%H%M%Y)
}

git-repack() {
  git repack -a -d -f --depth=250 --window=250
}

signoff() {
  docker-rm-rf
  docker system prune -f
  osascript -e 'quit app "Slack"'
}
