" Vundle
set nocompatible
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" Vundle managament
Bundle 'gmarik/vundle'
Bundle 'scrooloose/nerdtree'
Bundle 'scrooloose/nerdcommenter'
Bundle 'c9s/bufexplorer'
Bundle 'taglist.vim'
Bundle 'MarcWeber/vim-addon-mw-utils'
Bundle 'tomtom/tlib_vim'
Bundle 'garbas/vim-snipmate'
Bundle 'honza/snipmate-snippets'
Bundle 'jelera/vim-javascript-syntax'

filetype plugin indent on

" syntax highlighting
syntax on
set hlsearch

" tabs -> spaces
set tabstop=2
set shiftwidth=2
set expandtab
set softtabstop=2

" line number
set nu

" disable arrow keys
noremap  <Up> ""
noremap! <Up> <Esc>
noremap  <Down> ""
noremap! <Down> <Esc>
noremap  <Left> ""
noremap! <Left> <Esc>
noremap  <Right> ""
noremap! <Right> <Esc>

" color column
set colorcolumn=120

" color scheme
colorscheme wombat

" search case sensitivity
set smartcase

" backup
set backupdir=~/dotvim/backup,.
set directory=~/dotvim/swap,.
set undodir=~/dotvim/undo,.

" disable toolbar
if has("gui_running")
  set guioptions=egmrt
endif

" search highlight deleting
nnoremap <CR> :noh<CR><CR>

"""""""""""""" packages """"""""""""""

" TagList options
  "let Tlist_Close_On_Select = 1 "close taglist window once we selected something
let Tlist_Exit_OnlyWindow = 1 "if taglist window is the only window left, exit vim
let Tlist_Show_Menu = 1 "show Tags menu in gvim
let Tlist_Show_One_File = 1 "show tags of only one file
let Tlist_GainFocus_On_ToggleOpen = 1 "automatically switch to taglist window
let Tlist_Highlight_Tag_On_BufEnter = 1 "highlight current tag in taglist window
let Tlist_Process_File_Always = 1 "even without taglist window, create tags file, required for displaying tag in statusline
let Tlist_Use_Right_Window = 1 "display taglist window on the right
let Tlist_Display_Prototype = 1 "display full prototype instead of just function name
"let Tlist_Ctags_Cmd = /path/to/exuberant/ctags
nnoremap <F8> :TlistToggle<CR>
nnoremap <F6> :TlistShowPrototype
set statusline=[%n]\ %<%f\ %([%1*%M%*%R%Y]%)\ \ \ [%{Tlist_Get_Tagname_By_Line()}]\ %=%-19(\LINE\ [%l/%L]\ COL\ [%02c%03V]%)\ %P

" ctrlp
set runtimepath^=~/.vim/bundle/ctrlp/ctrlp.vim

" bufexplorer
let mapleader=","

" nerd tree
    "give a shortcut key to NERD Tree
map <F2> :NERDTreeToggle<CR> 
nnoremap <Leader>nt :NERDTreeToggle <CR>
nnoremap <Leader>nf :NERDTreeFind <CR>
let NERDTreeShowBookmarks=1
let NERDTreeShowHidden=1
    " let NERDTreeMinimalUI=1
let NERDTreeChDirMode=2
let NERDTreeIgnore=['\.DS_Store', '\.pyc', '\~$', 'target$[[dir]]', '\.class',
  \'\.swo$', '\.swp$', '\.git', '\.hg', '\.svn', '\.bzr', 'tags',
  \'\.project', 'target/']
